# Generated by Django 3.2.15 on 2022-08-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220822_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=150)),
                ('shop_address', models.CharField(max_length=200)),
                ('shop_logo', models.ImageField(upload_to='media')),
            ],
        ),
    ]
