# Generated by Django 3.2.15 on 2022-08-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_shop_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_logo',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
