# Generated by Django 3.2.15 on 2022-09-03 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_shop_shop_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
                ('category_description', models.TextField()),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shop', verbose_name='shop')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_purchase_price', models.FloatField()),
                ('item_sell_price', models.FloatField()),
                ('item_description', models.TextField()),
                ('item_image', models.ImageField(upload_to='media')),
                ('item_stock_count', models.IntegerField()),
                ('item_inventory_location', models.CharField(max_length=50)),
                ('item_purchase_date', models.DateField()),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='category')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shop', verbose_name='shop')),
            ],
        ),
    ]
