# Generated by Django 3.2.15 on 2022-09-17 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_category_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_inventory_location',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_purchase_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_purchase_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_stock_count',
        ),
        migrations.AddField(
            model_name='item',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
