# Generated by Django 3.0.5 on 2021-07-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210708_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ManyToManyField(to='api.Images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_meta_title',
            field=models.CharField(default='<django.db.models.fields.CharField> - Buy Online in Nepal at Best Price', max_length=80),
        ),
    ]
