# Generated by Django 3.0.5 on 2021-08-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210713_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_image', models.ImageField(upload_to='data/media/offer')),
                ('offer_text', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='data/media/users'),
        ),
    ]
