# Generated by Django 3.0.5 on 2021-08-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210812_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='images',
        ),
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ImageField(null=True, upload_to='data/media/category'),
        ),
    ]
