# Generated by Django 3.0.5 on 2021-09-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210926_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, default='/media/data/media/products/1.jpg', upload_to='data/media/products'),
        ),
    ]
